#!/bin/bash

rouge='\033[0;31m'
vert='\033[0;32m'
jaune='\033[0;33m'
neutre='\033[0;0m'

largeurTerminal=$(expr $(tput cols) - 1)
if !(test -z $1) && !(test -z $2) && (test $1 -ge $2)
	then
	max=$1
	actual=$2
else
	max=$2
	actual=$1
fi

first=1
while(!(test -z $3) || (test $first -eq 1))
do
	if !(test -z $3) && (test $3 = '-c') && !(test -z $4)
		then
		char=${4:0:1}
		shift
		shift
	else
		char='#'
	fi
	first=0
done
if !(test -z $actual) && !(test -z $max) && !(test -z $char)
	then
	percent=$(expr $(expr $actual \* $largeurTerminal) / $max)
	affichage=''
	i=0
	unTiers=$(expr $largeurTerminal \/ 3)
	deuxTiers=$(expr $unTiers + $unTiers)
	while(test $percent -ge 0)
	do
		if (test $i -ge $deuxTiers)
			then
		    echo -ne $affichage$rouge$char
		else
	    	if (test $i -ge $unTiers)
		   		then
		   		echo -ne $affichage$jaune$char
		    else
				echo -ne $affichage$vert$char
			fi
		fi
		percent=$(expr $percent - 1)
		i=$(expr $i + 1)
	done
	echo -e $neutre
else
	echo "usage: progress num num [-c char]"
fi